project:
  type: website
  output-dir: docs

website:
  title: "Hackaton2024"
  sidebar:
    left:
      - href: index.qmd
        text: "Index"
    right: 
      - icon: github # add icons as navbar buttons
        href: https://github.com/worldregio/hackaton2024
        target: _blank
  page-footer:
    background: dark
    left: Copyright 2024, Claude Grasland
format:
  html:
    theme: 
      light: minty    
      dark: solar
    css: styles.css
    toc: true


