project:
  type: website
  output-dir: docs

website:
  title: "Hackaton2024"
  sidebar:
    contents:
    - section: "INTRODUCTION"
      contents:
      - href: index.qmd
        text: "Objectifs"
      - href: 01-Data.qmd
        text: "Préparation des données"  
    - section: "DONNEES RP"
      contents: 
      - href: 02-agregation-sociale.qmd
        text: "Analyse sociologique"   
      - href: 03-agregation-spatiale.qmd
        text: "Agrégation par iris"   
      - href: 04-carto-statique.qmd
        text: "Cartographie mapsf" 
    - section: "DONNEES RPLS"
      contents: 
      - href: 05-exploration.qmd
        text: "Exploration"   
      - href: 06-agregation_point.qmd
        text: "Agrégation par iris ou adresse"   
      - href: 07-carto_dyn.qmd
        text: "Cartographie mapview"  
    - section: "ANALYSE SPATIALE"
      contents: 
      - href: 08-semis-de-points.qmd
        text: "Semis de points" 

  navbar:
    right: 
      - icon: github # add icons as navbar buttons
        href: https://github.com/worldregio/hackaton2024
        target: _blank
  page-footer:
    background: dark
    left: Copyright 2024, Claude Grasland, Pierre Pistre, Hadrien Commenges
format:
  html:
    theme: 
      light: minty    
      dark: solar
    code-fold: true
    css: styles.css
    toc: true


