project:
  type: website
  output-dir: docs

website:
  title: "Hackaton2024"
  sidebar:
    contents:
      - href: index.qmd
        text: "Objectifs"
      - href: 01-Data.qmd
        text: "Préparation des données"  
      - href: 02-agregation-sociale.qmd
        text: "Agrégation sociale"   
      - href: 03-agregation-spatiale.qmd
        text: "Agrégation spatiale"   
 
  navbar:
    right: 
      - icon: github # add icons as navbar buttons
        href: https://github.com/worldregio/hackaton2024
        target: _blank
  page-footer:
    background: dark
    left: Copyright 2024, Claude Grasland, Pierre Pistre, Hadrien Commenges
format:
  html:
    theme: 
      light: minty    
      dark: solar
    css: styles.css
    toc: true


